language: node_js
branches:
    only:
        - master
node_js:
  - "12"
cache:
  npm
services:
  - docker
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install gcc-4.9 -y
  - sudo apt-get install --only-upgrade libstdc++6 -y
  - wget https://github.com/mavlink/MAVSDK/releases/download/v0.23.0/mavsdk_0.23.0_ubuntu16.04_amd64.deb
  - sudo dpkg -i mavsdk_0.23.0_ubuntu16.04_amd64.deb
  - docker run -d -it --net=host jonasvautherin/px4-gazebo-headless:v1.9.2
before_script:
  - npx envinfo
script:
  - npm test
  - npm run build-docs
deploy:  
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  local_dir: docs
  on:
    branch: master

deploy:
  provider: npm
  skip_cleanup: true
  email: info@nodriver.ai
  api_key: $NPM_TOKEN
  on:
    branch: master